Fix compilation of http_upload.cc with gcc
Fix compilation of http_upload.cc with gcc after 548ca6e3, by moving the
definition of GetFileContents(), so it comes after the definition of
WideToMBCP(), which it uses.

common/windows/http_upload.cc: In function ‘bool {anonymous}::GetFileContents(const wstring&, std::vector<char>*)’:
common/windows/http_upload.cc:80:19: error: ‘WideToMBCP’ was not declared in this scope